export const ENV_MAILER_EMAIL = 'MAILER_EMAIL'

export const ENV_MAILER_PASSWORD = 'MAILER_PASSWORD'

export const ENV_DB_USERNAME = 'DB_USERNAME'

export const ENV_DB_PASSWORD = 'DB_PASSWORD'

export const ENV_ROLE_ADMIN_PASSWORD = 'ROLE_ADMIN_PASSWORD'

export const ENV_PASSWORD_HASH_ROUNDS = 'PASSWORD_HASH_ROUNDS'

export const ENV_DB_HOST = 'DB_HOST'

export const ENV_DB_PORT = 'DB_PORT'

export const ENV_DB_NAME = 'DB_NAME'

export const ENV_DB_SYNC = 'DB_SYNC'

export const ENV_JWT_SECRET_KEY = 'JWT_SECRET_KEY'